name: Sync Template Updates

on:
  workflow_dispatch: # Allow manual triggering
  repository_dispatch:
    types: [update-template]

jobs:
  sync-template:
    if: github.repository != 'purduerov/board-template'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
        with:
          submodules: recursive

      - name: Sync with board-template
        uses: AndreasAugustin/actions-template-sync@5362c4f8ee36a9e356adf24b8abc5462550664b3  # v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: purduerov/board-template
          upstream_branch: master
          is_pr: true

